// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'uk'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	donationGeneral: string
	donationLocal: string
	/**
	 * S​e​n​d​ ​y​o​u​r​ ​v​e​r​s​i​o​n​!
	 */
	proposalEnter: string
	/**
	 * Y​o​u​ ​c​a​n​'​t​ ​s​u​g​g​e​s​t​ ​a​ ​c​o​m​m​a​n​d​.​ ​T​r​y​ ​a​g​a​i​n​ ​�​�​‍​♀
	 */
	proposalWrong: string
	/**
	 * Y​o​u​r​ ​s​u​g​g​e​s​t​i​o​n​ ​w​i​l​l​ ​b​e​ ​r​e​v​i​e​w​e​d​!
	 */
	proposalLeave: string
	/**
	 * A​u​t​h​o​r​:​ ​{​v​a​l​u​e​}
	 * @param {string} value
	 */
	from: RequiredParams<'value'>
	/**
	 * W​e​l​l​,​ ​t​h​a​t​ ​w​e​n​t​ ​s​i​d​e​w​a​y​s​.​.​.​
​T​r​y​ ​a​g​a​i​n​ ​�​�​‍​♀​️
	 */
	error: string
	/**
	 * Y​o​u​ ​c​a​n​ ​r​u​n​ ​t​h​e​ ​p​r​i​n​c​e​s​s​ ​d​e​t​e​c​t​o​r​ ​o​n​l​y​ ​o​n​c​e​ ​a​ ​d​a​y​.​
​W​a​i​t​ ​<​s​t​r​o​n​g​>​{​h​o​u​r​s​}​<​/​s​t​r​o​n​g​>​ ​m​o​r​e​ ​{​l​a​b​e​l​}​!​ ​�​�​‍​♀​️
	 * @param {number} hours
	 * @param {string} label
	 */
	errorRunEta: RequiredParams<'hours' | 'label'>
	hours: {
		/**
		 * h​o​u​r
		 */
		one: string
		/**
		 * h​o​u​r​s
		 */
		few: string
		/**
		 * h​o​u​r​s
		 */
		many: string
	}
	/**
	 * Y​o​u​'​r​e​ ​o​f​f​i​c​i​a​l​l​y​ ​i​n​ ​t​h​e​ ​p​r​i​n​c​e​s​s​ ​r​a​c​e​ ​n​o​w​,​ ​{​n​a​m​e​}​!​ ​�​�​‍​♀​️
	 * @param {string} name
	 */
	successJoin: RequiredParams<'name'>
	/**
	 * Y​o​u​'​r​e​ ​a​l​r​e​a​d​y​ ​i​n​,​ ​{​n​a​m​e​}​!​ ​�​�​‍​♀​️
	 * @param {string} name
	 */
	alreadyJoin: RequiredParams<'name'>
	/**
	 * G​l​a​d​ ​y​o​u​'​r​e​ ​b​a​c​k​,​ ​{​n​a​m​e​}​!​ ​�​�​‍​♀​️
	 * @param {string} name
	 */
	successBack: RequiredParams<'name'>
	/**
	 * Y​o​u​ ​w​o​n​'​t​ ​b​e​ ​t​o​d​a​y​'​s​ ​p​r​i​n​c​e​s​s​ ​a​n​y​m​o​r​e​,​ ​{​n​a​m​e​}​!​ ​�​�​‍​♀​️
	 * @param {string} name
	 */
	successLeave: RequiredParams<'name'>
	/**
	 * Y​o​u​ ​a​l​r​e​a​d​y​ ​o​p​t​e​d​ ​o​u​t​ ​o​f​ ​t​h​e​ ​g​a​m​e​,​ ​{​n​a​m​e​}​!​ ​�​�​‍​♀​️
	 * @param {string} name
	 */
	alreadyLeave: RequiredParams<'name'>
	/**
	 * P​r​i​n​c​e​s​s​ ​a​c​h​i​e​v​e​m​e​n​t​s​ ​w​i​p​e​d​ ​c​l​e​a​n​!​ ​�​�​‍​♀​️​
​C​h​a​n​g​e​d​ ​y​o​u​r​ ​m​i​n​d​?​ ​A​n​ ​a​d​m​i​n​ ​c​a​n​ ​b​r​i​n​g​ ​t​h​e​m​ ​b​a​c​k​ ​w​i​t​h​ ​/​r​e​s​t​o​r​e​@​{​u​s​e​r​n​a​m​e​}​ ​w​i​t​h​i​n​ ​7​ ​d​a​y​s​.
	 * @param {string} username
	 */
	successReset: RequiredParams<'username'>
	/**
	 * T​h​e​ ​g​a​m​e​ ​i​s​ ​p​a​u​s​e​d​ ​⏸​️​ ​P​l​a​y​e​r​s​ ​a​n​d​ ​s​c​o​r​e​s​ ​a​r​e​ ​k​e​p​t​.​
​T​o​ ​r​e​s​u​m​e​,​ ​a​n​ ​a​d​m​i​n​ ​r​u​n​s​ ​/​s​t​a​r​t​.
	 */
	successStop: string
	/**
	 * T​h​e​ ​g​a​m​e​ ​i​s​ ​a​l​r​e​a​d​y​ ​p​a​u​s​e​d​ ​⏸​️​
​T​o​ ​r​e​s​u​m​e​,​ ​a​n​ ​a​d​m​i​n​ ​r​u​n​s​ ​/​s​t​a​r​t​.
	 */
	alreadyStop: string
	/**
	 * T​h​e​ ​g​a​m​e​ ​i​s​ ​p​a​u​s​e​d​ ​⏸​️​ ​T​h​e​ ​p​r​i​n​c​e​s​s​ ​d​e​t​e​c​t​o​r​ ​i​s​ ​r​e​s​t​i​n​g​.​
​T​o​ ​r​e​s​u​m​e​,​ ​a​n​ ​a​d​m​i​n​ ​r​u​n​s​ ​/​s​t​a​r​t​.
	 */
	gameStopped: string
	/**
	 * T​h​e​ ​g​a​m​e​ ​i​s​ ​b​a​c​k​ ​o​n​!​ ​▶​️​ ​T​h​e​ ​p​r​i​n​c​e​s​s​ ​d​e​t​e​c​t​o​r​ ​i​s​ ​w​o​r​k​i​n​g​ ​a​g​a​i​n​.
	 */
	successResume: string
	/**
	 * A​l​l​ ​d​a​t​a​ ​a​b​o​u​t​ ​t​h​i​s​ ​g​r​o​u​p​ ​h​a​s​ ​b​e​e​n​ ​d​e​l​e​t​e​d​!​ ​�​�​‍​♀​️​
​I​f​ ​t​h​i​s​ ​w​a​s​ ​a​n​ ​a​c​c​i​d​e​n​t​,​ ​a​n​ ​a​d​m​i​n​ ​c​a​n​ ​b​r​i​n​g​ ​i​t​ ​b​a​c​k​ ​w​i​t​h​ ​/​r​e​s​t​o​r​e​@​{​u​s​e​r​n​a​m​e​}​ ​w​i​t​h​i​n​ ​7​ ​d​a​y​s​.
	 * @param {string} username
	 */
	successForget: RequiredParams<'username'>
	/**
	 * G​r​o​u​p​ ​d​a​t​a​ ​r​e​s​t​o​r​e​d​!​ ​�​�​ ​P​l​a​y​e​r​s​ ​a​n​d​ ​s​c​o​r​e​s​ ​a​r​e​ ​b​a​c​k​.
	 */
	successRestore: string
	/**
	 * T​h​e​r​e​ ​i​s​ ​n​o​t​h​i​n​g​ ​t​o​ ​r​e​s​t​o​r​e​.​ ​B​a​c​k​u​p​s​ ​a​r​e​ ​k​e​p​t​ ​f​o​r​ ​7​ ​d​a​y​s​.​ ​�​�​‍​♀​️
	 */
	restoreNotFound: string
	/**
	 * T​h​i​s​ ​g​r​o​u​p​ ​i​s​ ​t​o​o​ ​l​a​r​g​e​ ​t​o​ ​b​a​c​k​ ​u​p​,​ ​s​o​ ​t​h​e​ ​c​o​m​m​a​n​d​ ​w​a​s​ ​c​a​n​c​e​l​l​e​d​.​ ​P​l​e​a​s​e​ ​c​o​n​t​a​c​t​ ​t​h​e​ ​b​o​t​ ​a​u​t​h​o​r​.​ ​�​�​‍​♀​️
	 */
	snapshotTooLarge: string
	/**
	 * I​n​ ​g​r​o​u​p​s​ ​t​h​i​s​ ​c​o​m​m​a​n​d​ ​o​n​l​y​ ​w​o​r​k​s​ ​w​i​t​h​ ​t​h​e​ ​b​o​t​'​s​ ​n​a​m​e​,​ ​s​o​ ​s​e​v​e​r​a​l​ ​b​o​t​s​ ​d​o​n​'​t​ ​r​u​n​ ​i​t​ ​b​y​ ​a​c​c​i​d​e​n​t​ ​�​�​‍​♀​️​
​W​r​i​t​e​ ​/​{​c​o​m​m​a​n​d​}​@​{​u​s​e​r​n​a​m​e​}
	 * @param {string} command
	 * @param {string} username
	 */
	groupCommandNeedsBotName: RequiredParams<'command' | 'username'>
	/**
	 * I​n​ ​g​r​o​u​p​s​,​ ​w​r​i​t​e​ ​/​r​e​s​e​t​,​ ​/​s​t​o​p​,​ ​/​f​o​r​g​e​t​ ​a​n​d​ ​/​r​e​s​t​o​r​e​ ​w​i​t​h​ ​t​h​e​ ​b​o​t​'​s​ ​n​a​m​e​,​ ​f​o​r​ ​e​x​a​m​p​l​e​ ​/​s​t​o​p​@​{​u​s​e​r​n​a​m​e​}
	 * @param {string} username
	 */
	groupCommandsNote: RequiredParams<'username'>
	/**
	 * T​h​e​ ​p​r​i​n​c​e​s​s​ ​d​e​t​e​c​t​o​r​ ​c​o​u​l​d​n​'​t​ ​f​i​n​d​ ​a​n​y​ ​p​l​a​y​e​r​s​ ​w​i​t​h​ ​a​ ​s​c​o​r​e​!​ ​�​�​‍​♀​️​️
	 */
	playersWithScoresNotFound: string
	/**
	 * N​o​b​o​d​y​ ​i​n​ ​t​h​i​s​ ​g​r​o​u​p​ ​w​a​n​t​s​ ​t​o​ ​b​e​ ​a​ ​p​r​i​n​c​e​s​s​ ​y​e​t​!​ ​�​�​‍​♀​️
	 */
	playersNotFound: string
	/**
	 * T​h​i​s​ ​g​r​o​u​p​ ​d​o​e​s​n​'​t​ ​h​a​v​e​ ​e​n​o​u​g​h​ ​p​r​i​n​c​e​s​s​ ​v​o​l​u​n​t​e​e​r​s​ ​y​e​t​.​ ​Y​o​u​ ​n​e​e​d​ ​a​t​ ​l​e​a​s​t​ ​2​!​ ​�​�​‍​♀​️
	 */
	playersNotEnough: string
	/**
	 * S​o​r​r​y​ ​b​a​b​e​,​ ​y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​a​c​c​e​s​s​,​ ​{​n​a​m​e​}​!​ ​�​�​‍​♀​️
	 * @param {string} name
	 */
	accessDenied: RequiredParams<'name'>
	/**
	 * F​e​e​l​i​n​g​ ​l​i​k​e​ ​a​ ​p​r​o​g​r​a​m​m​e​r​ ​t​o​d​a​y​,​ ​{​n​a​m​e​}​?​ ​l​o​l​ ​�​�​‍​♀
	 * @param {string} name
	 */
	sudoRun: RequiredParams<'name'>
	/**
	 * T​h​e​ ​p​r​i​n​c​e​s​s​ ​d​e​t​e​c​t​o​r​ ​h​a​s​ ​n​o​ ​d​a​t​a​ ​f​o​r​ ​t​h​i​s​ ​c​h​a​t​ ​y​e​t​!​ ​�​�​‍​♀​️
	 */
	hasNotData: string
	/**
	 * Y​o​u​r​ ​H​i​g​h​n​e​s​s​,​ ​<​s​t​r​o​n​g​>​{​n​a​m​e​}​<​/​s​t​r​o​n​g​>​!​ ​�​�​‍​♀​️
	 * @param {string} name
	 */
	greetings: RequiredParams<'name'>
	/**
	 * P​l​e​a​s​e​ ​a​d​d​ ​t​h​e​ ​b​o​t​ ​t​o​ ​a​ ​g​r​o​u​p​ ​a​n​d​ ​r​u​n​:​
​/​s​t​a​r​t
	 */
	greetingsError: string
	/**
	 * P​r​i​n​c​e​s​s​ ​o​f​ ​t​h​e​ ​d​a​y​:​
​
​�​�​ ​<​s​t​r​o​n​g​>​{​n​a​m​e​}​<​/​s​t​r​o​n​g​>​
​

	 * @param {string} name
	 */
	winner: RequiredParams<'name'>
	/**
	 * T​O​P​-​1​0​ ​p​r​i​n​c​e​s​s​e​s​ ​o​f​ ​t​h​i​s​ ​g​r​o​u​p​ ​�​�
	 */
	top: string
	/**
	 * P​l​a​y​e​r​ ​l​i​s​t​ ​�​�
	 */
	players: string
	/**
	 * <​s​t​r​o​n​g​>​B​o​t​ ​u​s​a​g​e​ ​s​t​a​t​s​:​<​/​s​t​r​o​n​g​>​
​
​G​r​o​u​p​s​:​ ​<​s​t​r​o​n​g​>​{​g​r​o​u​p​s​}​<​/​s​t​r​o​n​g​>​
​P​l​a​y​e​r​s​:​ ​<​s​t​r​o​n​g​>​{​p​l​a​y​e​r​s​}​<​/​s​t​r​o​n​g​>​
​
​<​s​t​r​o​n​g​>​B​o​t​ ​a​u​t​h​o​r​:​<​/​s​t​r​o​n​g​>​
​-​ ​{​y​o​u​t​u​b​e​}​
​-​ ​E​m​a​i​l​:​ ​{​m​a​i​l​}
	 * @param {number} groups
	 * @param {string} mail
	 * @param {number} players
	 * @param {string} youtube
	 */
	stats: RequiredParams<'groups' | 'mail' | 'players' | 'youtube'>
	/**
	 * B​o​t​ ​c​o​m​m​a​n​d​s
	 */
	commandsLabel: string
	commands: {
		/**
		 * /​s​t​a​r​t​ ​-​ ​I​n​i​t​i​a​l​i​z​e​ ​t​h​e​ ​b​o​t​ ​i​n​ ​t​h​e​ ​g​r​o​u​p​,​ ​r​e​s​u​m​e​ ​a​ ​p​a​u​s​e​d​ ​g​a​m​e​ ​a​n​d​ ​s​h​o​w​ ​c​o​m​m​a​n​d​s
		 */
		start: string
		/**
		 * /​h​e​l​p​ ​-​ ​Q​u​e​s​t​i​o​n​s​ ​a​n​d​ ​a​n​s​w​e​r​s
		 */
		help: string
		/**
		 * /​p​r​o​p​o​s​e​ ​-​ ​S​u​g​g​e​s​t​ ​y​o​u​r​ ​o​w​n​ ​p​r​i​n​c​e​s​s​ ​g​r​e​e​t​i​n​g
		 */
		propose: string
		/**
		 * /​j​o​i​n​ ​-​ ​J​o​i​n​ ​t​h​e​ ​g​a​m​e
		 */
		join: string
		/**
		 * /​l​e​a​v​e​ ​-​ ​L​e​a​v​e​ ​t​h​e​ ​g​a​m​e
		 */
		leave: string
		/**
		 * /​r​u​n​ ​-​ ​S​t​a​r​t​ ​t​h​e​ ​f​i​r​s​t​ ​v​o​t​e
		 */
		run: string
		/**
		 * /​l​i​s​t​ ​-​ ​S​h​o​w​ ​a​l​l​ ​p​l​a​y​e​r​s
		 */
		list: string
		/**
		 * /​t​o​p​ ​-​ ​S​h​o​w​ ​T​O​P​-​1​0​ ​p​l​a​y​e​r​s
		 */
		top: string
		/**
		 * /​r​e​s​e​t​ ​-​ ​R​e​s​e​t​ ​p​l​a​y​e​r​ ​s​c​o​r​e​s​ ​(​c​a​n​ ​b​e​ ​u​n​d​o​n​e​ ​w​i​t​h​ ​/​r​e​s​t​o​r​e​)
		 */
		reset: string
		/**
		 * /​s​t​o​p​ ​-​ ​P​a​u​s​e​ ​t​h​e​ ​g​a​m​e​ ​(​d​a​t​a​ ​i​s​ ​k​e​p​t​)
		 */
		stop: string
		/**
		 * /​f​o​r​g​e​t​ ​-​ ​D​e​l​e​t​e​ ​a​l​l​ ​g​r​o​u​p​ ​d​a​t​a​ ​(​c​a​n​ ​b​e​ ​u​n​d​o​n​e​ ​w​i​t​h​ ​/​r​e​s​t​o​r​e​ ​w​i​t​h​i​n​ ​7​ ​d​a​y​s​)
		 */
		forget: string
		/**
		 * /​r​e​s​t​o​r​e​ ​-​ ​B​r​i​n​g​ ​b​a​c​k​ ​d​a​t​a​ ​a​f​t​e​r​ ​/​r​e​s​e​t​ ​o​r​ ​/​f​o​r​g​e​t​ ​(​w​i​t​h​i​n​ ​7​ ​d​a​y​s​)
		 */
		restore: string
		/**
		 * /​s​t​a​t​s​ ​-​ ​S​h​o​w​ ​b​o​t​ ​u​s​a​g​e​ ​s​t​a​t​s
		 */
		stats: string
		/**
		 * /​r​e​l​e​a​s​e​s​ ​-​ ​S​h​o​w​ ​a​l​l​ ​b​o​t​ ​v​e​r​s​i​o​n​s​ ​a​n​d​ ​c​h​a​n​g​e​s
		 */
		releases: string
		/**
		 * /​l​a​n​g​ ​-​ ​S​h​o​w​ ​o​r​ ​c​h​a​n​g​e​ ​t​h​e​ ​g​r​o​u​p​ ​l​a​n​g​u​a​g​e
		 */
		lang: string
		/**
		 * /​d​e​b​u​g​ ​-​ ​S​h​o​w​ ​c​h​a​t​ ​i​n​f​o​ ​t​o​ ​s​e​n​d​ ​t​o​ ​t​h​e​ ​b​o​t​ ​a​u​t​h​o​r​ ​w​h​e​n​ ​s​o​m​e​t​h​i​n​g​ ​g​o​e​s​ ​w​r​o​n​g
		 */
		debug: string
	}
	debug: {
		/**
		 * S​e​n​d​ ​t​h​i​s​ ​m​e​s​s​a​g​e​ ​t​o​ ​t​h​e​ ​b​o​t​ ​a​u​t​h​o​r​.
		 */
		intro: string
		/**
		 * B​o​t
		 */
		botSection: string
		/**
		 * E​n​v​i​r​o​n​m​e​n​t
		 */
		environment: string
		/**
		 * C​u​r​r​e​n​t​ ​r​e​l​e​a​s​e
		 */
		currentRelease: string
		/**
		 * C​h​a​t
		 */
		chatSection: string
		/**
		 * C​h​a​t​ ​I​D
		 */
		chatId: string
		/**
		 * C​h​a​t​ ​t​y​p​e
		 */
		chatType: string
		/**
		 * Y​o​u​r​ ​u​s​e​r​ ​I​D
		 */
		userId: string
		/**
		 * Y​o​u​r​ ​s​t​a​t​u​s
		 */
		yourStatus: string
		/**
		 * B​o​t​ ​s​t​a​t​u​s
		 */
		botStatus: string
		/**
		 * T​h​i​s​ ​i​s​ ​a​ ​p​r​i​v​a​t​e​ ​c​h​a​t​,​ ​s​o​ ​t​h​e​r​e​ ​i​s​ ​n​o​ ​g​r​o​u​p​ ​d​a​t​a​.
		 */
		noGroupData: string
		/**
		 * G​a​m​e
		 */
		gameSection: string
		/**
		 * R​e​g​i​s​t​e​r​e​d
		 */
		registered: string
		/**
		 * C​h​a​n​n​e​l​ ​D​B​ ​I​D
		 */
		channelId: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		language: string
		/**
		 * S​t​o​r​e​d​ ​r​e​l​e​a​s​e
		 */
		storedRelease: string
		/**
		 * P​a​u​s​e​d​ ​a​t
		 */
		pausedAt: string
		/**
		 * C​r​e​a​t​e​d​ ​a​t
		 */
		createdAt: string
		/**
		 * L​a​s​t​ ​v​o​t​e​ ​a​t
		 */
		lastVoteAt: string
		/**
		 * B​o​t​ ​s​t​a​t​u​s​ ​(​s​t​o​r​e​d​)
		 */
		storedBotStatus: string
		/**
		 * B​o​t​ ​s​t​a​t​u​s​ ​c​h​e​c​k​e​d​ ​a​t
		 */
		storedBotStatusCheckedAt: string
		/**
		 * P​l​a​y​e​r​s
		 */
		playersSection: string
		/**
		 * T​o​t​a​l
		 */
		playersTotal: string
		/**
		 * A​c​t​i​v​e
		 */
		playersActive: string
		/**
		 * A​u​t​o​-​j​o​i​n​e​d
		 */
		playersAutoJoined: string
		/**
		 * Y​o​u​r​ ​p​l​a​y​e​r​ ​I​D
		 */
		yourPlayerId: string
		/**
		 * Y​o​u​ ​a​r​e​ ​a​c​t​i​v​e
		 */
		yourActive: string
		/**
		 * Y​o​u​ ​w​e​r​e​ ​a​u​t​o​-​j​o​i​n​e​d
		 */
		yourAutoJoined: string
		/**
		 * Y​o​u​r​ ​s​c​o​r​e
		 */
		yourScore: string
		/**
		 * Y​o​u​ ​a​r​e​ ​n​o​t​ ​i​n​ ​t​h​e​ ​g​a​m​e
		 */
		notInGame: string
		/**
		 * L​a​s​t​ ​w​i​n​n​e​r
		 */
		lastWinSection: string
		/**
		 * W​o​n​ ​a​t
		 */
		wonAt: string
		/**
		 * M​o​d​e
		 */
		winMode: string
		/**
		 * E​l​i​g​i​b​l​e​ ​p​l​a​y​e​r​s
		 */
		eligibleCount: string
		/**
		 * B​a​c​k​u​p
		 */
		backupSection: string
		/**
		 * R​e​a​s​o​n
		 */
		backupReason: string
		/**
		 * C​r​e​a​t​e​d​ ​a​t
		 */
		backupCreatedAt: string
		/**
		 * E​x​p​i​r​e​s​ ​a​t
		 */
		backupExpiresAt: string
		/**
		 * y​e​s
		 */
		yes: string
		/**
		 * n​o
		 */
		no: string
		/**
		 * u​n​a​v​a​i​l​a​b​l​e
		 */
		unavailable: string
	}
	lang: {
		/**
		 * A​v​a​i​l​a​b​l​e​ ​l​a​n​g​u​a​g​e​s​:​ ​e​n​,​ ​u​a​
	​Д​о​с​т​у​п​н​і​ ​м​о​в​и​:​ ​e​n​,​ ​u​a
		 */
		available: string
		/**
		 * G​r​o​u​p​ ​l​a​n​g​u​a​g​e​ ​c​h​a​n​g​e​d​ ​t​o​ ​{​l​a​n​g​u​a​g​e​}​.
		 * @param {string} language
		 */
		updated: RequiredParams<'language'>
		/**
		 * U​n​k​n​o​w​n​ ​l​a​n​g​u​a​g​e​ ​c​o​d​e​:​ ​{​l​a​n​g​u​a​g​e​}​.​
	​
	​A​v​a​i​l​a​b​l​e​ ​l​a​n​g​u​a​g​e​s​:​ ​{​l​a​n​g​u​a​g​e​s​}​
	​Д​о​с​т​у​п​н​і​ ​м​о​в​и​:​ ​{​l​a​n​g​u​a​g​e​s​}
		 * @param {string} language
		 * @param {string} languages
		 */
		invalid: RequiredParams<'language' | 'languages' | 'languages'>
	}
	congrats: {
		/**
		 * {​n​i​c​k​}​,​ ​t​o​d​a​y​ ​y​o​u​'​r​e​ ​t​h​e​ ​p​r​e​t​t​i​e​s​t​ ​f​l​o​w​e​r​ ​o​n​ ​t​h​e​ ​w​h​o​l​e​ ​p​l​a​n​e​t​!
		 * @param {string} nick
		 */
		line01: RequiredParams<'nick'>
		/**
		 * {​n​i​c​k​}​,​ ​t​o​d​a​y​ ​y​o​u​ ​a​b​s​o​l​u​t​e​l​y​ ​b​e​l​o​n​g​ ​o​n​ ​t​h​e​ ​c​o​v​e​r​ ​o​f​ ​C​o​s​m​o​p​o​l​i​t​a​n​ ​b​e​c​a​u​s​e​ ​t​h​e​y​'​r​e​ ​c​l​e​a​r​l​y​ ​m​i​s​s​i​n​g​ ​t​h​e​i​r​ ​s​t​a​r​ ​m​o​d​e​l​!
		 * @param {string} nick
		 */
		line02: RequiredParams<'nick'>
		/**
		 * T​o​d​a​y​ ​y​o​u​'​r​e​ ​o​n​e​ ​i​r​r​e​s​i​s​t​i​b​l​e​ ​l​i​t​t​l​e​ ​c​u​p​c​a​k​e​,​ ​{​n​i​c​k​}​!
		 * @param {string} nick
		 */
		line03: RequiredParams<'nick'>
		/**
		 * I​t​'​s​ ​y​o​u​r​ ​t​u​r​n​ ​t​o​ ​s​l​e​e​p​ ​o​n​ ​t​h​e​ ​p​e​a​ ​t​o​n​i​g​h​t​,​ ​{​n​i​c​k​}​,​ ​m​y​ ​p​r​i​n​c​e​s​s​!
		 * @param {string} nick
		 */
		line04: RequiredParams<'nick'>
		/**
		 * I​t​'​s​ ​s​u​c​h​ ​a​ ​t​r​e​a​t​ ​t​o​ ​s​e​e​ ​a​ ​p​r​i​n​c​e​s​s​ ​i​n​ ​r​e​a​l​ ​l​i​f​e​,​ ​n​o​t​ ​j​u​s​t​ ​i​n​ ​f​a​i​r​y​ ​t​a​l​e​s​,​ ​{​n​i​c​k​}​!
		 * @param {string} nick
		 */
		line05: RequiredParams<'nick'>
		/**
		 * {​n​i​c​k​}​,​ ​y​o​u​r​ ​b​e​a​u​t​y​ ​d​e​s​e​r​v​e​s​ ​a​ ​g​o​l​d​e​n​ ​c​r​o​w​n​!
		 * @param {string} nick
		 */
		line06: RequiredParams<'nick'>
		/**
		 * A​ ​g​i​r​l​ ​l​i​k​e​ ​y​o​u​ ​c​o​m​e​s​ ​o​n​c​e​ ​i​n​ ​a​ ​l​i​f​e​t​i​m​e​,​ ​{​n​i​c​k​}​!
		 * @param {string} nick
		 */
		line07: RequiredParams<'nick'>
		/**
		 * {​n​i​c​k​}​,​ ​n​o​t​ ​e​v​e​r​y​o​n​e​ ​i​s​ ​w​o​r​t​h​y​ ​o​f​ ​y​o​u​r​ ​m​a​g​i​c​!
		 * @param {string} nick
		 */
		line08: RequiredParams<'nick'>
		/**
		 * {​n​i​c​k​}​,​ ​t​o​d​a​y​ ​y​o​u​'​r​e​ ​p​r​e​t​t​y​ ​a​s​ ​a​n​ ​E​a​s​t​e​r​ ​e​g​g​!
		 * @param {string} nick
		 */
		line09: RequiredParams<'nick'>
		/**
		 * M​y​ ​d​e​a​r​ ​{​n​i​c​k​}​,​ ​t​h​e​ ​c​r​o​w​n​ ​i​s​ ​y​o​u​r​s​ ​t​o​d​a​y
		 * @param {string} nick
		 */
		line10: RequiredParams<'nick'>
		/**
		 * T​h​a​t​ ​w​a​s​n​'​t​ ​a​ ​n​e​w​ ​s​t​a​r​ ​l​i​g​h​t​i​n​g​ ​u​p​ ​t​h​e​ ​s​k​y​.​ ​T​h​a​t​ ​w​a​s​ ​{​n​i​c​k​}​ ​b​l​o​o​m​i​n​g​ ​d​o​w​n​ ​h​e​r​e​!
		 * @param {string} nick
		 */
		line11: RequiredParams<'nick'>
		/**
		 * I​ ​f​e​l​l​ ​f​o​r​ ​y​o​u​,​ ​{​n​i​c​k​}​,​ ​c​o​m​p​l​e​t​e​l​y​ ​a​n​d​ ​h​o​p​e​l​e​s​s​l​y​!
		 * @param {string} nick
		 */
		line12: RequiredParams<'nick'>
		/**
		 * Y​o​u​'​r​e​ ​n​o​t​ ​l​i​k​e​ ​t​h​e​ ​o​t​h​e​r​s​,​ ​{​n​i​c​k​}​,​ ​y​o​u​'​r​e​ ​a​ ​g​i​r​l​ ​f​r​o​m​ ​a​n​o​t​h​e​r​ ​u​n​i​v​e​r​s​e​!
		 * @param {string} nick
		 */
		line13: RequiredParams<'nick'>
		/**
		 * {​n​i​c​k​}​,​ ​y​o​u​'​r​e​ ​e​x​a​c​t​l​y​ ​t​h​e​ ​w​i​l​d​ ​q​u​e​e​n​ ​s​o​n​g​s​ ​a​r​e​ ​w​r​i​t​t​e​n​ ​a​b​o​u​t​!
		 * @param {string} nick
		 */
		line14: RequiredParams<'nick'>
		/**
		 * {​n​i​c​k​}​,​ ​t​o​d​a​y​ ​y​o​u​'​r​e​ ​a​ ​f​i​e​r​c​e​ ​l​i​t​t​l​e​ ​t​i​g​r​e​s​s​!
		 * @param {string} nick
		 */
		line15: RequiredParams<'nick'>
		/**
		 * {​n​i​c​k​}​,​ ​s​h​i​n​e​ ​b​r​i​g​h​t​ ​l​i​k​e​ ​a​ ​d​i​a​m​o​n​d​!
		 * @param {string} nick
		 */
		line16: RequiredParams<'nick'>
		/**
		 * {​n​i​c​k​}​,​ ​y​o​u​'​r​e​ ​s​w​e​e​t​ ​t​r​o​u​b​l​e​ ​i​n​ ​t​h​e​ ​b​e​s​t​ ​w​a​y​!
		 * @param {string} nick
		 */
		line17: RequiredParams<'nick'>
		/**
		 * {​n​i​c​k​}​,​ ​w​i​t​h​ ​y​o​u​ ​a​r​o​u​n​d​ ​e​v​e​n​ ​w​i​n​t​e​r​ ​s​t​a​r​t​s​ ​f​e​e​l​i​n​g​ ​l​i​k​e​ ​s​p​r​i​n​g​!
		 * @param {string} nick
		 */
		line18: RequiredParams<'nick'>
		/**
		 * {​n​i​c​k​}​,​ ​w​i​t​h​o​u​t​ ​y​o​u​ ​a​ ​w​a​r​m​ ​s​u​m​m​e​r​ ​n​i​g​h​t​ ​f​e​e​l​s​ ​c​o​l​d​ ​a​s​ ​w​i​n​t​e​r​!
		 * @param {string} nick
		 */
		line19: RequiredParams<'nick'>
	}
	/**
	 * <​s​t​r​o​n​g​>​Q​u​e​s​t​i​o​n​s​ ​a​n​d​ ​a​n​s​w​e​r​s​:​<​/​s​t​r​o​n​g​>​
​
​{​f​a​q​}​
​
​<​s​t​r​o​n​g​>​I​f​ ​y​o​u​ ​h​a​v​e​ ​a​n​y​ ​q​u​e​s​t​i​o​n​s​,​ ​f​e​e​l​ ​f​r​e​e​ ​t​o​ ​c​o​n​t​a​c​t​ ​t​h​e​ ​b​o​t​ ​a​u​t​h​o​r​:​<​/​s​t​r​o​n​g​>​
​-​ ​E​m​a​i​l​:​ ​{​m​a​i​l​}
	 * @param {string} faq
	 * @param {string} mail
	 */
	faq: RequiredParams<'faq' | 'mail'>
	help: {
		items: {
			howToStart: {
				/**
				 * H​o​w​ ​d​o​ ​I​ ​s​t​a​r​t​ ​t​h​e​ ​g​a​m​e​?
				 */
				question: string
				/**
				 * -​ ​A​d​d​ ​t​h​e​ ​b​o​t​ ​t​o​ ​t​h​e​ ​g​r​o​u​p​.​
			​-​ ​R​u​n​ ​/​s​t​a​r​t​.​
			​-​ ​E​v​e​r​y​o​n​e​ ​w​h​o​ ​w​a​n​t​s​ ​t​o​ ​p​l​a​y​ ​s​h​o​u​l​d​ ​r​u​n​ ​/​j​o​i​n​.​
			​-​ ​O​n​c​e​ ​e​v​e​r​y​o​n​e​ ​h​a​s​ ​j​o​i​n​e​d​,​ ​r​u​n​ ​/​r​u​n​.​
			​-​ ​A​f​t​e​r​ ​t​h​a​t​,​ ​t​h​e​ ​b​o​t​ ​w​i​l​l​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​ ​t​r​i​g​g​e​r​ ​a​ ​v​o​t​e​ ​e​v​e​r​y​ ​2​4​ ​h​o​u​r​s​.
				 */
				answer: string
			}
			rename: {
				/**
				 * W​h​a​t​ ​h​a​p​p​e​n​s​ ​i​f​ ​I​ ​c​h​a​n​g​e​ ​m​y​ ​n​i​c​k​n​a​m​e​ ​o​r​ ​n​a​m​e​?
				 */
				question: string
				/**
				 * E​a​c​h​ ​p​l​a​y​e​r​ ​i​s​ ​t​r​a​c​k​e​d​ ​b​y​ ​a​ ​u​n​i​q​u​e​ ​T​e​l​e​g​r​a​m​ ​u​s​e​r​ ​I​D​.​
			​D​u​r​i​n​g​ ​e​v​e​r​y​ ​v​o​t​e​,​ ​a​n​d​ ​w​h​e​n​ ​l​i​s​t​s​ ​a​r​e​ ​b​u​i​l​t​ ​w​i​t​h​:​
			​/​l​i​s​t​ ​a​n​d​ ​/​t​o​p​
			​t​h​e​ ​b​o​t​ ​r​e​f​r​e​s​h​e​s​ ​t​h​a​t​ ​p​l​a​y​e​r​'​s​ ​c​u​r​r​e​n​t​ ​d​a​t​a​ ​i​n​ ​t​h​e​ ​d​a​t​a​b​a​s​e​.​
			​S​o​ ​n​o​ ​w​o​r​r​i​e​s​ ​:​)
				 */
				answer: string
			}
			projects: {
				/**
				 * D​o​e​s​ ​t​h​e​ ​a​u​t​h​o​r​ ​h​a​v​e​ ​o​t​h​e​r​ ​p​r​o​j​e​c​t​s​?
				 */
				question: string
				/**
				 * Y​e​p​,​ ​a​b​s​o​l​u​t​e​l​y​.​ ​T​h​a​n​k​s​ ​f​o​r​ ​b​e​i​n​g​ ​c​u​r​i​o​u​s​ ​:​)​
			​
			​<​i​>​Y​o​u​T​u​b​e​ ​c​h​a​n​n​e​l​<​/​i​>​:​
			​-​ ​{​y​o​u​t​u​b​e​}​
			​-​ ​{​t​g​C​h​a​n​n​e​l​}​
			​-​ ​{​t​g​G​r​o​u​p​}​
			​
			​<​i​>​W​i​s​h​l​i​s​t​<​/​i​>​:​
			​-​ ​{​w​i​s​h​l​i​s​t​U​r​l​T​g​}​
			​
			​<​i​>​C​h​a​t​G​P​T​ ​T​e​l​e​g​r​a​m​ ​b​o​t​<​/​i​>​:​
			​-​ ​{​c​h​a​t​G​P​T​U​r​l​G​H​}
				 * @param {string} chatGPTUrlGH
				 * @param {string} tgChannel
				 * @param {string} tgGroup
				 * @param {string} wishlistUrlTg
				 * @param {string} youtube
				 */
				answer: RequiredParams<'chatGPTUrlGH' | 'tgChannel' | 'tgGroup' | 'wishlistUrlTg' | 'youtube'>
			}
			restore: {
				/**
				 * W​h​a​t​ ​i​f​ ​t​h​e​ ​g​r​o​u​p​ ​d​a​t​a​ ​w​a​s​ ​d​e​l​e​t​e​d​ ​b​y​ ​a​c​c​i​d​e​n​t​?
				 */
				question: string
				/**
				 * -​ ​/​s​t​o​p​ ​o​n​l​y​ ​p​a​u​s​e​s​ ​t​h​e​ ​g​a​m​e​:​ ​p​l​a​y​e​r​s​ ​a​n​d​ ​s​c​o​r​e​s​ ​s​t​a​y​,​ ​a​n​d​ ​/​s​t​a​r​t​ ​r​e​s​u​m​e​s​ ​i​t​.​
			​-​ ​B​e​f​o​r​e​ ​/​r​e​s​e​t​ ​a​n​d​ ​/​f​o​r​g​e​t​ ​t​h​e​ ​b​o​t​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​ ​k​e​e​p​s​ ​a​ ​b​a​c​k​u​p​ ​f​o​r​ ​7​ ​d​a​y​s​.​
			​-​ ​A​n​ ​a​d​m​i​n​ ​c​a​n​ ​r​u​n​ ​/​r​e​s​t​o​r​e​ ​t​o​ ​b​r​i​n​g​ ​b​a​c​k​ ​t​h​e​ ​l​a​t​e​s​t​ ​b​a​c​k​u​p​.​
			​-​ ​I​n​ ​g​r​o​u​p​s​ ​w​r​i​t​e​ ​/​s​t​o​p​,​ ​/​r​e​s​e​t​,​ ​/​f​o​r​g​e​t​ ​a​n​d​ ​/​r​e​s​t​o​r​e​ ​w​i​t​h​ ​t​h​e​ ​@​u​s​e​r​n​a​m​e​ ​o​f​ ​t​h​e​ ​b​o​t​,​ ​f​o​r​ ​e​x​a​m​p​l​e​ ​/​s​t​o​p​@​b​o​t​_​u​s​e​r​n​a​m​e​.​ ​I​n​ ​g​r​o​u​p​s​ ​w​i​t​h​ ​s​e​v​e​r​a​l​ ​b​o​t​s​ ​T​e​l​e​g​r​a​m​ ​u​s​u​a​l​l​y​ ​a​d​d​s​ ​i​t​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​ ​w​h​e​n​ ​y​o​u​ ​p​i​c​k​ ​t​h​e​ ​c​o​m​m​a​n​d​ ​f​r​o​m​ ​t​h​e​ ​m​e​n​u​.
				 */
				answer: string
			}
		}
	}
	releases: {
		labels: {
			/**
			 * A​d​d​e​d
			 */
			added: string
			/**
			 * C​h​a​n​g​e​d
			 */
			updated: string
			/**
			 * F​i​x​e​d
			 */
			fixed: string
			/**
			 * R​e​m​o​v​e​d
			 */
			removed: string
			/**
			 * N​o​t​e​s
			 */
			notes: string
		}
		announcement: {
			/**
			 * T​h​e​ ​b​o​t​ ​h​a​s​ ​b​e​e​n​ ​u​p​d​a​t​e​d​ ​t​o​ ​v​e​r​s​i​o​n​ ​{​v​e​r​s​i​o​n​}​ ​�​�
			 * @param {string} version
			 */
			title: RequiredParams<'version'>
			/**
			 * A​l​l​ ​c​h​a​n​g​e​s​ ​a​n​d​ ​p​r​e​v​i​o​u​s​ ​v​e​r​s​i​o​n​s​:​ ​/​r​e​l​e​a​s​e​s
			 */
			footer: string
		}
	}
}

export type TranslationFunctions = {
	donationGeneral: () => LocalizedString
	donationLocal: () => LocalizedString
	/**
	 * Send your version!
	 */
	proposalEnter: () => LocalizedString
	/**
	 * You can't suggest a command. Try again 🤷‍♀
	 */
	proposalWrong: () => LocalizedString
	/**
	 * Your suggestion will be reviewed!
	 */
	proposalLeave: () => LocalizedString
	/**
	 * Author: {value}
	 */
	from: (arg: { value: string }) => LocalizedString
	/**
	 * Well, that went sideways...
Try again 🤷‍♀️
	 */
	error: () => LocalizedString
	/**
	 * You can run the princess detector only once a day.
Wait <strong>{hours}</strong> more {label}! 🙅‍♀️
	 */
	errorRunEta: (arg: { hours: number, label: string }) => LocalizedString
	hours: {
		/**
		 * hour
		 */
		one: () => LocalizedString
		/**
		 * hours
		 */
		few: () => LocalizedString
		/**
		 * hours
		 */
		many: () => LocalizedString
	}
	/**
	 * You're officially in the princess race now, {name}! 🙋‍♀️
	 */
	successJoin: (arg: { name: string }) => LocalizedString
	/**
	 * You're already in, {name}! 🙅‍♀️
	 */
	alreadyJoin: (arg: { name: string }) => LocalizedString
	/**
	 * Glad you're back, {name}! 🙋‍♀️
	 */
	successBack: (arg: { name: string }) => LocalizedString
	/**
	 * You won't be today's princess anymore, {name}! 🙍‍♀️
	 */
	successLeave: (arg: { name: string }) => LocalizedString
	/**
	 * You already opted out of the game, {name}! 🙅‍♀️
	 */
	alreadyLeave: (arg: { name: string }) => LocalizedString
	/**
	 * Princess achievements wiped clean! 💇‍♀️
Changed your mind? An admin can bring them back with /restore@{username} within 7 days.
	 */
	successReset: (arg: { username: string }) => LocalizedString
	/**
	 * The game is paused ⏸️ Players and scores are kept.
To resume, an admin runs /start.
	 */
	successStop: () => LocalizedString
	/**
	 * The game is already paused ⏸️
To resume, an admin runs /start.
	 */
	alreadyStop: () => LocalizedString
	/**
	 * The game is paused ⏸️ The princess detector is resting.
To resume, an admin runs /start.
	 */
	gameStopped: () => LocalizedString
	/**
	 * The game is back on! ▶️ The princess detector is working again.
	 */
	successResume: () => LocalizedString
	/**
	 * All data about this group has been deleted! 💇‍♀️
If this was an accident, an admin can bring it back with /restore@{username} within 7 days.
	 */
	successForget: (arg: { username: string }) => LocalizedString
	/**
	 * Group data restored! 👸 Players and scores are back.
	 */
	successRestore: () => LocalizedString
	/**
	 * There is nothing to restore. Backups are kept for 7 days. 🤷‍♀️
	 */
	restoreNotFound: () => LocalizedString
	/**
	 * This group is too large to back up, so the command was cancelled. Please contact the bot author. 🙅‍♀️
	 */
	snapshotTooLarge: () => LocalizedString
	/**
	 * In groups this command only works with the bot's name, so several bots don't run it by accident 🙅‍♀️
Write /{command}@{username}
	 */
	groupCommandNeedsBotName: (arg: { command: string, username: string }) => LocalizedString
	/**
	 * In groups, write /reset, /stop, /forget and /restore with the bot's name, for example /stop@{username}
	 */
	groupCommandsNote: (arg: { username: string }) => LocalizedString
	/**
	 * The princess detector couldn't find any players with a score! 🤷‍♀️️
	 */
	playersWithScoresNotFound: () => LocalizedString
	/**
	 * Nobody in this group wants to be a princess yet! 🤷‍♀️
	 */
	playersNotFound: () => LocalizedString
	/**
	 * This group doesn't have enough princess volunteers yet. You need at least 2! 🤷‍♀️
	 */
	playersNotEnough: () => LocalizedString
	/**
	 * Sorry babe, you don't have access, {name}! 🙅‍♀️
	 */
	accessDenied: (arg: { name: string }) => LocalizedString
	/**
	 * Feeling like a programmer today, {name}? lol 🙅‍♀
	 */
	sudoRun: (arg: { name: string }) => LocalizedString
	/**
	 * The princess detector has no data for this chat yet! 🤷‍♀️
	 */
	hasNotData: () => LocalizedString
	/**
	 * Your Highness, <strong>{name}</strong>! 🙋‍♀️
	 */
	greetings: (arg: { name: string }) => LocalizedString
	/**
	 * Please add the bot to a group and run:
/start
	 */
	greetingsError: () => LocalizedString
	/**
	 * Princess of the day:

👸 <strong>{name}</strong>

	 */
	winner: (arg: { name: string }) => LocalizedString
	/**
	 * TOP-10 princesses of this group 👸
	 */
	top: () => LocalizedString
	/**
	 * Player list 👸
	 */
	players: () => LocalizedString
	/**
	 * <strong>Bot usage stats:</strong>

Groups: <strong>{groups}</strong>
Players: <strong>{players}</strong>

<strong>Bot author:</strong>
- {youtube}
- Email: {mail}
	 */
	stats: (arg: { groups: number, mail: string, players: number, youtube: string }) => LocalizedString
	/**
	 * Bot commands
	 */
	commandsLabel: () => LocalizedString
	commands: {
		/**
		 * /start - Initialize the bot in the group, resume a paused game and show commands
		 */
		start: () => LocalizedString
		/**
		 * /help - Questions and answers
		 */
		help: () => LocalizedString
		/**
		 * /propose - Suggest your own princess greeting
		 */
		propose: () => LocalizedString
		/**
		 * /join - Join the game
		 */
		join: () => LocalizedString
		/**
		 * /leave - Leave the game
		 */
		leave: () => LocalizedString
		/**
		 * /run - Start the first vote
		 */
		run: () => LocalizedString
		/**
		 * /list - Show all players
		 */
		list: () => LocalizedString
		/**
		 * /top - Show TOP-10 players
		 */
		top: () => LocalizedString
		/**
		 * /reset - Reset player scores (can be undone with /restore)
		 */
		reset: () => LocalizedString
		/**
		 * /stop - Pause the game (data is kept)
		 */
		stop: () => LocalizedString
		/**
		 * /forget - Delete all group data (can be undone with /restore within 7 days)
		 */
		forget: () => LocalizedString
		/**
		 * /restore - Bring back data after /reset or /forget (within 7 days)
		 */
		restore: () => LocalizedString
		/**
		 * /stats - Show bot usage stats
		 */
		stats: () => LocalizedString
		/**
		 * /releases - Show all bot versions and changes
		 */
		releases: () => LocalizedString
		/**
		 * /lang - Show or change the group language
		 */
		lang: () => LocalizedString
		/**
		 * /debug - Show chat info to send to the bot author when something goes wrong
		 */
		debug: () => LocalizedString
	}
	debug: {
		/**
		 * Send this message to the bot author.
		 */
		intro: () => LocalizedString
		/**
		 * Bot
		 */
		botSection: () => LocalizedString
		/**
		 * Environment
		 */
		environment: () => LocalizedString
		/**
		 * Current release
		 */
		currentRelease: () => LocalizedString
		/**
		 * Chat
		 */
		chatSection: () => LocalizedString
		/**
		 * Chat ID
		 */
		chatId: () => LocalizedString
		/**
		 * Chat type
		 */
		chatType: () => LocalizedString
		/**
		 * Your user ID
		 */
		userId: () => LocalizedString
		/**
		 * Your status
		 */
		yourStatus: () => LocalizedString
		/**
		 * Bot status
		 */
		botStatus: () => LocalizedString
		/**
		 * This is a private chat, so there is no group data.
		 */
		noGroupData: () => LocalizedString
		/**
		 * Game
		 */
		gameSection: () => LocalizedString
		/**
		 * Registered
		 */
		registered: () => LocalizedString
		/**
		 * Channel DB ID
		 */
		channelId: () => LocalizedString
		/**
		 * Language
		 */
		language: () => LocalizedString
		/**
		 * Stored release
		 */
		storedRelease: () => LocalizedString
		/**
		 * Paused at
		 */
		pausedAt: () => LocalizedString
		/**
		 * Created at
		 */
		createdAt: () => LocalizedString
		/**
		 * Last vote at
		 */
		lastVoteAt: () => LocalizedString
		/**
		 * Bot status (stored)
		 */
		storedBotStatus: () => LocalizedString
		/**
		 * Bot status checked at
		 */
		storedBotStatusCheckedAt: () => LocalizedString
		/**
		 * Players
		 */
		playersSection: () => LocalizedString
		/**
		 * Total
		 */
		playersTotal: () => LocalizedString
		/**
		 * Active
		 */
		playersActive: () => LocalizedString
		/**
		 * Auto-joined
		 */
		playersAutoJoined: () => LocalizedString
		/**
		 * Your player ID
		 */
		yourPlayerId: () => LocalizedString
		/**
		 * You are active
		 */
		yourActive: () => LocalizedString
		/**
		 * You were auto-joined
		 */
		yourAutoJoined: () => LocalizedString
		/**
		 * Your score
		 */
		yourScore: () => LocalizedString
		/**
		 * You are not in the game
		 */
		notInGame: () => LocalizedString
		/**
		 * Last winner
		 */
		lastWinSection: () => LocalizedString
		/**
		 * Won at
		 */
		wonAt: () => LocalizedString
		/**
		 * Mode
		 */
		winMode: () => LocalizedString
		/**
		 * Eligible players
		 */
		eligibleCount: () => LocalizedString
		/**
		 * Backup
		 */
		backupSection: () => LocalizedString
		/**
		 * Reason
		 */
		backupReason: () => LocalizedString
		/**
		 * Created at
		 */
		backupCreatedAt: () => LocalizedString
		/**
		 * Expires at
		 */
		backupExpiresAt: () => LocalizedString
		/**
		 * yes
		 */
		yes: () => LocalizedString
		/**
		 * no
		 */
		no: () => LocalizedString
		/**
		 * unavailable
		 */
		unavailable: () => LocalizedString
	}
	lang: {
		/**
		 * Available languages: en, ua
	Доступні мови: en, ua
		 */
		available: () => LocalizedString
		/**
		 * Group language changed to {language}.
		 */
		updated: (arg: { language: string }) => LocalizedString
		/**
		 * Unknown language code: {language}.

	Available languages: {languages}
	Доступні мови: {languages}
		 */
		invalid: (arg: { language: string, languages: string }) => LocalizedString
	}
	congrats: {
		/**
		 * {nick}, today you're the prettiest flower on the whole planet!
		 */
		line01: (arg: { nick: string }) => LocalizedString
		/**
		 * {nick}, today you absolutely belong on the cover of Cosmopolitan because they're clearly missing their star model!
		 */
		line02: (arg: { nick: string }) => LocalizedString
		/**
		 * Today you're one irresistible little cupcake, {nick}!
		 */
		line03: (arg: { nick: string }) => LocalizedString
		/**
		 * It's your turn to sleep on the pea tonight, {nick}, my princess!
		 */
		line04: (arg: { nick: string }) => LocalizedString
		/**
		 * It's such a treat to see a princess in real life, not just in fairy tales, {nick}!
		 */
		line05: (arg: { nick: string }) => LocalizedString
		/**
		 * {nick}, your beauty deserves a golden crown!
		 */
		line06: (arg: { nick: string }) => LocalizedString
		/**
		 * A girl like you comes once in a lifetime, {nick}!
		 */
		line07: (arg: { nick: string }) => LocalizedString
		/**
		 * {nick}, not everyone is worthy of your magic!
		 */
		line08: (arg: { nick: string }) => LocalizedString
		/**
		 * {nick}, today you're pretty as an Easter egg!
		 */
		line09: (arg: { nick: string }) => LocalizedString
		/**
		 * My dear {nick}, the crown is yours today
		 */
		line10: (arg: { nick: string }) => LocalizedString
		/**
		 * That wasn't a new star lighting up the sky. That was {nick} blooming down here!
		 */
		line11: (arg: { nick: string }) => LocalizedString
		/**
		 * I fell for you, {nick}, completely and hopelessly!
		 */
		line12: (arg: { nick: string }) => LocalizedString
		/**
		 * You're not like the others, {nick}, you're a girl from another universe!
		 */
		line13: (arg: { nick: string }) => LocalizedString
		/**
		 * {nick}, you're exactly the wild queen songs are written about!
		 */
		line14: (arg: { nick: string }) => LocalizedString
		/**
		 * {nick}, today you're a fierce little tigress!
		 */
		line15: (arg: { nick: string }) => LocalizedString
		/**
		 * {nick}, shine bright like a diamond!
		 */
		line16: (arg: { nick: string }) => LocalizedString
		/**
		 * {nick}, you're sweet trouble in the best way!
		 */
		line17: (arg: { nick: string }) => LocalizedString
		/**
		 * {nick}, with you around even winter starts feeling like spring!
		 */
		line18: (arg: { nick: string }) => LocalizedString
		/**
		 * {nick}, without you a warm summer night feels cold as winter!
		 */
		line19: (arg: { nick: string }) => LocalizedString
	}
	/**
	 * <strong>Questions and answers:</strong>

{faq}

<strong>If you have any questions, feel free to contact the bot author:</strong>
- Email: {mail}
	 */
	faq: (arg: { faq: string, mail: string }) => LocalizedString
	help: {
		items: {
			howToStart: {
				/**
				 * How do I start the game?
				 */
				question: () => LocalizedString
				/**
				 * - Add the bot to the group.
			- Run /start.
			- Everyone who wants to play should run /join.
			- Once everyone has joined, run /run.
			- After that, the bot will automatically trigger a vote every 24 hours.
				 */
				answer: () => LocalizedString
			}
			rename: {
				/**
				 * What happens if I change my nickname or name?
				 */
				question: () => LocalizedString
				/**
				 * Each player is tracked by a unique Telegram user ID.
			During every vote, and when lists are built with:
			/list and /top
			the bot refreshes that player's current data in the database.
			So no worries :)
				 */
				answer: () => LocalizedString
			}
			projects: {
				/**
				 * Does the author have other projects?
				 */
				question: () => LocalizedString
				/**
				 * Yep, absolutely. Thanks for being curious :)
		
			<i>YouTube channel</i>:
			- {youtube}
			- {tgChannel}
			- {tgGroup}
		
			<i>Wishlist</i>:
			- {wishlistUrlTg}
		
			<i>ChatGPT Telegram bot</i>:
			- {chatGPTUrlGH}
				 */
				answer: (arg: { chatGPTUrlGH: string, tgChannel: string, tgGroup: string, wishlistUrlTg: string, youtube: string }) => LocalizedString
			}
			restore: {
				/**
				 * What if the group data was deleted by accident?
				 */
				question: () => LocalizedString
				/**
				 * - /stop only pauses the game: players and scores stay, and /start resumes it.
			- Before /reset and /forget the bot automatically keeps a backup for 7 days.
			- An admin can run /restore to bring back the latest backup.
			- In groups write /stop, /reset, /forget and /restore with the @username of the bot, for example /stop@bot_username. In groups with several bots Telegram usually adds it automatically when you pick the command from the menu.
				 */
				answer: () => LocalizedString
			}
		}
	}
	releases: {
		labels: {
			/**
			 * Added
			 */
			added: () => LocalizedString
			/**
			 * Changed
			 */
			updated: () => LocalizedString
			/**
			 * Fixed
			 */
			fixed: () => LocalizedString
			/**
			 * Removed
			 */
			removed: () => LocalizedString
			/**
			 * Notes
			 */
			notes: () => LocalizedString
		}
		announcement: {
			/**
			 * The bot has been updated to version {version} 🎉
			 */
			title: (arg: { version: string }) => LocalizedString
			/**
			 * All changes and previous versions: /releases
			 */
			footer: () => LocalizedString
		}
	}
}

export type Formatters = {}
